### PR TITLE
Narayan's CLI added

### PR DESCRIPTION
**Pull request by narayanpai1**

### CODE REVIEW

**Review by YashasG98 — CHANGES_REQUESTED** [review]
'batchfile.txt' mentioned in readme has not been included. The file is working fine.

**Comment by YashasG98** [comment]
Also include instructions on how to change the permissions of your 'shell' executable.

**Comment by YashasG98** [comment]
Also, add a list of known bugs, if any.

**Comment by narayanpai1** [comment]
I have changed the permissions myself and added batchfile.txt

**Review by YashasG98 — APPROVED** [review]

**Pull request merged**
