### PR TITLE
Ajay Bharadwaj's CLI + Web Server

### PR DESCRIPTION
**Pull request by AnorexicAtticusFinch**
Added Ajay Bharadwaj's Implementation of the CLI (with the cd command being executed separately with the chdir() system call)

### CODE REVIEW

**Review by YashasG98 — CHANGES_REQUESTED** [review]
Create a readme file inside your CLI folder and include instructions on how to run the file in batch mode and how to change permissions of the executable to be able to run it on any system.

**Review by YashasG98 — COMMENTED** [review]
Also add a list of known bugs, if any.

**Comment by AnorexicAtticusFinch** [comment]
@YashasG98 Made the changes

**Comment by AnorexicAtticusFinch** [comment]
Added the basic web server code
Client: Makes 1 connection at a time (Only serial mode)
Server: Can handle multiple requests at the same time but in a sloppy way that simply creates a new thread for each request i.e. there is no request buffer and the number of threads is not fixed

**Review by YashasG98 — APPROVED** [review]

**Pull request merged**
